export enum ActionTypes {
  SET_LOCATION = 'SET_LOCATION',
  SET_LOCATION_FULFILLED = 'SET_LOCATION_FULFILLED',
  SET_LOCATION_PENDING = 'SET_LOCATION_PENDING',
  SET_LOCATION_REJECTED = 'SET_LOCATION_REJECTED',
};
