export enum ActionTypes {
  SET_LOCATION = 'SET_LOCATION',
  SET_LOCATION_FULFILLED = 'SET_LOCATION_FULFILLED',
  SET_LOCATION_PENDING = 'SET_LOCATION_PENDING',
  SET_LOCATION_REJECTED = 'SET_LOCATION_REJECTED',
  SET_FILTER = 'SET_FILTER',
  SET_FILTER_FULFILLED = 'SET_FILTER_FULFILLED',
  SET_FILTER_PENDING = 'SET_FILTER_PENDING',
  SET_FILTER_REJECTED = 'SET_FILTER_REJECTED',
};
