export enum ActionTypes {
  OPEN_NAVIGATION = "OPEN_NAVIGATION",
  OPEN_NAVIGATION_FULFILLED = "OPEN_NAVIGATION_FULFILLED",
  CLOSE_NAVIGATION = "CLOSE_NAVIGATION",
  CLOSE_NAVIGATION_FULFILLED = "CLOSE_NAVIGATION_FULFILLED"
}
